name: RustyServerPipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # Add to the matrix.os any additional os I want to build for.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

     # Note that SonarCloud currently doesn't support Rust language Analysis

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORG}}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY}}

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        projectBaseDir: .
